### ISSUE TITLE
Polyfill is never useful?

### ISSUE THREAD

**Issue by ljharb** [seznam/IMA.js-babel6-polyfill#2]
https://github.com/seznam/IMA.js-babel6-polyfill/blob/master/index.js#L4 looks like it polyfills only when `Object.setPrototypeOf` does not exist, **and** when `({}).__proto__` does not exist. In this scenario, `Object.getPrototypeOf` is impossible to polyfill.

The only thing I can think of that this does is creates a function that uses a `__proto__` data property in `getPrototypeOf`, despite that property having no special meaning in that engine. Is that accurate? If so,  then that seems to mean that this is only attempting to support Babel's usage of calling `getPrototypeOf` after setting `__proto__`?

**Comment by ondras** [comment]
Hi @ljharb,

this polyfill aims at Babel's class inheritance mechanism which can be observed at [this code sample](http://babeljs.io/repl/#?evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&playground=false&code=class%20A%20%7B%7D%0Aclass%20B%20extends%20A%20%7B%7D%0A): `__proto__` is used as a fallback where no `setPrototypeOf` is available.

IE8-10 implements `getPrototypeOf` but no `setPrototypeof`, so Babel uses the `__proto__` code path. We thus have to patch the (existing native) implementation of `getPrototypeOf` to account for `__proto__` if necessary.

You are correct that the code in question is not really a polyfill. More of a compatibility fix.

**Comment by ljharb** [comment]
Thanks for clarifying :-)
